### ISSUE TITLE
Sélection des équipes pour match

### ISSUE THREAD

**Issue by lelie21** [BMunier/pronostics#7]
Problème remonté que seul 20 équipes apparaissent dans la drop-down. Après tentative de l'interface sur mobile, le problème n'est pas présent sur mobile.

**Comment by lelie21** [comment]
Petite précision. En version mobile il n'y en a que 29 sur les 32.

**Comment by lelie21** [comment]
Il y a un truc qui m'échappe. Le code ISO que l'on met dans les entités pays sont sur deux positions et celui de la liste des pays dans match sur 3. Est on sur que la source de données est la même? C'est sûrement une question con mais je demande

**Comment by lelie21** [comment]
question con, ce sont pas la pays mais les equipes. résultat, je sais pas ce qui a été fait mais ca marche bien sur mobile comme sur Ordi (chrome)

**Comment by BMunier** [comment]
Merci pour les remarques par contre tu n'es pas sur le bon projet.

C'est celui-ci qui est déployé --> https://github.com/BMunier/pronostics-jdl

**Comment by lelie21** [comment]
ah wai je suspectais un probleme vu le vide sidéral du projet et l'inactivité 
mais je testais la version deployée sur heroku.
